bitcoind:
  image: bitcoind
  volumes:
    - /bitcoin:/root/.bitcoin
ethereum:
  image: ethereum
  volumes:
    - /ethereum:/root/.ethereum
zcashd:
  image: zcashd
  volumes:
    - /zcash:/root/.zcash
